### ISSUE TITLE
Specific word filtering

### ISSUE THREAD

**Issue by Hirabunny** [rstuven/OpenTweetFilter#43]
Whenever I filter out certain words, it also filters out separate words that contain that word when I'd really like to just filter out the word alone. For example, filtering out "ass" would also filter out "asset" or "assassin" etc. That's not the word I'm filtering, but it's the same concept. I've tried adding spaces around my word to indicate that it should be a standalone word, but it didn't work. 

Is there a way to make it so that it only filters out the exact word? I've poked around but I haven't found any way to make this work, so I'd like an option perhaps similar to the /\W/ setting. People who like filtering out entire blocks of words can still do so, but if we want something more specific, we can have that. I'm not fully sure this is within the realm of possibility, but I'd really appreciate it if you could do something like it!

**Comment by rstuven** [comment]
Yes, regular expressions are supported. For your example, `/\bass\b/ `will make it (where `\b` matches a word boundary).
There is a nice tutorial about regular expressions in OpenTweetFilter here: http://polkabecky.tumblr.com/post/47123081478/reducing-twitter-noise-with-open-tweet-filter#examples
